on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          sudo pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: build

    outputs:
      tests_passed: ${{ steps.test_result.outputs.tests_passed }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          sudo pip install -r requirements.txt

      - name: Run tests
        id: test_result
        run: |
          # Execute your testing scripts, assuming pytest is used
          pytest test_app.py
          echo "::set-output name=tests_passed::true"  # Set the output if tests pass
        continue-on-error: true  # Continue even if tests fail

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging' && needs.test.outputs.tests_passed == 'true'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: actions/setup-ssh-action@v3
      with:
        github_secret_tokens: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to Main branch
      run: |
        ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} -p ${{ secrets.PORT }} << EOF
          cd /home/ubuntu/  # Replace with the correct path
          git fetch
          git checkout -b main origin/staging
          # Additional deployment steps if needed
        EOF
